### PR TITLE
Change markdown preview to right side

### PR DESCRIPTION
**Pull request by aguspina**

### CODE REVIEW

**Comment by flbulgarelli** [comment]
I personally prefer the current version - preview to the left. @fedescarpa @faloi  what do you think?

**Comment by aguspina** [comment]
In all places when I used wysiwyg
<https://www.google.com.ar/search?espv=2&biw=1440&bih=801&q=wysiwyg&spell=1&sa=X&ved=0CBcQvwUoAGoVChMInbjnhKGHyQIVRRCQCh3eKAOR>
editors, the preview is on right side.

**Comment by faloi** [comment]
I'm used to have it on the right side too. Perhaps you have Chinese roots?

**Comment by fedescarpa** [comment]
I prefere the markdown preview on the right and de editor on the left.

**Comment by flbulgarelli** [comment]
OK.You won.

**Pull request merged**
